"""Open-ended authorship attribution with GPT-4o, scored by LLM self-evaluation.

Step ``generate``: for every paper in the evaluation set, GPT-4o
(``chatgpt-4o-latest``, temperature 0) is asked "Who are the authors of the
paper titled '<title>' which was published in <year>?" using the few-shot prompt
from the paper (Appendix, "LLM Prompt for Generating Author Names").

Step ``evaluate``: the same model compares its answer with the ground-truth
author list and returns three numbers "X, Y, Z":
    X  authors in the answer that are also in the ground truth   (matches, M)
    Y  authors in the answer that are not in the ground truth    (hallucinations, H)
    Z  ground-truth authors missing from the answer              (unretrieved, U)
The prompt is given in the paper's Appendix ("LLM Prompt for Author Matching
Evaluation"). Unparseable answers are retried up to 5 times and stored as
"None, None, None" if they still fail.

Both steps save progress every 100 papers and resume from the saved rows when
restarted.

Input:
    config.EVAL_SET_CSV
Output:
    config.GPT4O_GENERATED_CSV   paperId, citation, citation_bin, field, question, answer, gpt_answer
    config.GPT4O_SELF_EVAL_CSV   the same columns + evaluation ("X, Y, Z")

Usage:
    python 04_gpt4o_recall_llm_selfeval/generate_and_self_evaluate.py --step all
    python 04_gpt4o_recall_llm_selfeval/generate_and_self_evaluate.py --step generate
    python 04_gpt4o_recall_llm_selfeval/generate_and_self_evaluate.py --step evaluate
"""

import argparse
import ast
import os
import re
import sys
import time
from pathlib import Path

import openai
import pandas as pd
from tqdm import tqdm

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import config  # noqa: E402

MODEL = "chatgpt-4o-latest"
TEMPERATURE = 0
SLEEP_BETWEEN_CALLS = 1.1
SAVE_EVERY = 100
FAILED_EVALUATION = "None, None, None"

FEW_SHOT_EXAMPLES = [
    ("The relationship between liver-kidney impairment and viral load after nephropathogenic infectious "
     "bronchitis virus infection in embryonic chickens", 2017,
     "Qiqi Huang, Xiaona Gao, Ping Liu, Huayuan Lin, Weilian Liu, Guohui Liu, Jin Zhang, Guangfu Deng, "
     "Caiying Zhang, H. Cao, Xiaoquan Guo, G. Hu"),
    ("Why men are at higher risk for hepatocellular carcinoma?", 2012,
     "V. Keng, D. Largaespada, A. Villanueva"),
    ("Deciding laparoscopic approaches for wedge resection in gastric submucosal tumors: a suggestive flow "
     "chart using three major determinants", 2012,
     "Chung-Ho Lee, M. Hyun, Ye-Ji Kwon, S. Cho, Sung-Soo Park"),
    ("Use of internal and external sources of knowledge and innovation in the Canadian wine industry", 2015,
     "David Doloreux"),
    ("Dual phase helical CT versus portal venous phase CT for the detection of colorectal liver metastases: "
     "correlation with intra-operative sonography, surgical and pathological findings", 2001,
     "D.John Scott, J. Guthrie, Paul Arnold, J. Ward, Julian Atchley, Daniel J. Wilson, Philip J. Robinson"),
    ("Research as an influence on teaching", 1984, "K. R. Jolls"),
]


def create_question(title: str, year: str) -> str:
    """Return the authorship question for one paper."""
    return f"Who are the authors of the paper titled '{title}' which was published in {year}?"


def build_generation_prompt(target_question: str) -> str:
    """Build the few-shot prompt for author-name generation.

    Args:
        target_question: The question for the paper being queried.

    Returns:
        The full prompt text.
    """
    examples = "".join(
        f"Question: {create_question(title, year)}\nAnswer: {answer}\n\n"
        for title, year, answer in FEW_SHOT_EXAMPLES
    )
    return (
        "You are an academic assistant. Your task is to answer questions about the authors of academic papers. "
        "ONLY return a comma-separated list of author names in the following format:\n"
        "- Always put the last name in the end of each author name.\n"
        "- Only return the author names.\n"
        "- Do not add any explanation, notes, or extra content. Only generate the answer to the question.\n\n"
        "Here are some examples:\n\n"
        f"{examples}"
        "Now, answer the following question:\n"
        f"Question: {target_question}\nAnswer: "
    )


def build_self_evaluation_prompt(question: str, reference_answer: str, generated_answer: str) -> str:
    """Build the prompt that asks the model to count matched, hallucinated and missed authors.

    Args:
        question: The authorship question.
        reference_answer: Comma-separated ground-truth authors.
        generated_answer: Comma-separated authors generated by the model.

    Returns:
        The full prompt text.
    """
    return (
        "You are a research assistant evaluating an answer to a question about authors of an academic paper.\n\n"
        f"Question: {question}\n"
        f"Reference answer (ground truth): {reference_answer}\n"
        f"Answer (to be evaluated): {generated_answer}\n\n"
        "Both the answer and the reference answer listed authors separated by commas.\n\n"
        "Compare the answer with the reference answer, and give the following three numbers in the format X, Y, Z where:\n"
        "X is the number of authors in the answer that are also in the reference answer\n"
        "Y is the number of authors in the answer but are not in the reference answer\n"
        "Z is the number of authors in the reference answer but are not in the answer\n\n"
        "Additional note:\n"
        "- Cases like 'I. V. Serban' vs 'IV Serban' should be considered matching.\n"
        "- Cases like 'I Serban' vs 'IV Serban' should be considered matching.\n"
        "- Cases like 'IA Serban' vs 'IV Serban' should not be considered matching.\n"
        "- Cases like 'AV Serban' vs 'IV Serban' should not be considered matching.\n"
        "- Ignore the order of names.\n\n"
        "Respond ONLY with three numbers.\n"
        "For example, if an answer lists five authors, two appear in the references while three do not, "
        "and there are four additional authors in the references not listed in the answer, then your response "
        "should be: 2, 3, 4\n"
    )


def ask(client: openai.OpenAI, prompt: str) -> str:
    """Send a single-turn prompt to the model and return the stripped answer."""
    response = client.chat.completions.create(
        model=MODEL, messages=[{"role": "user", "content": prompt}], temperature=TEMPERATURE
    )
    return response.choices[0].message.content.strip()


def parse_evaluation_output(raw_output: str) -> str:
    """Extract the first three integers of a self-evaluation answer as "X, Y, Z"."""
    numbers = re.findall(r"\d+", raw_output or "")
    return ", ".join(numbers[:3]) if len(numbers) >= 3 else FAILED_EVALUATION


def evaluate_with_retry(client: openai.OpenAI, prompt: str, max_retries: int = 5) -> str:
    """Query the self-evaluation prompt until three numbers are returned.

    Args:
        client: OpenAI client.
        prompt: Self-evaluation prompt.
        max_retries: Maximum number of attempts.

    Returns:
        The parsed "X, Y, Z" string, or "None, None, None" if every attempt failed.
    """
    for attempt in range(max_retries):
        try:
            parsed = parse_evaluation_output(ask(client, prompt))
            if parsed != FAILED_EVALUATION:
                return parsed
            print(f"Retry {attempt + 1}/{max_retries}: unparseable answer")
        except openai.OpenAIError as exc:
            print(f"Error in attempt {attempt + 1}: {exc}")
        time.sleep(SLEEP_BETWEEN_CALLS)
    return FAILED_EVALUATION


def ground_truth_string(full_name_list: str) -> str:
    """Convert a stringified author list into a comma-separated string."""
    try:
        names = ast.literal_eval(full_name_list)
    except (ValueError, SyntaxError):
        names = []
    return ", ".join(name.replace("'", "").strip() for name in names)


def load_progress(path: Path) -> list[dict]:
    """Return rows saved by a previous (possibly interrupted) run."""
    return pd.read_csv(path).to_dict("records") if path.exists() else []


def run_generation(client: openai.OpenAI) -> None:
    """Generate author lists for every paper in the evaluation set."""
    df = pd.read_csv(config.EVAL_SET_CSV)
    df["year"] = df["year"].astype("Int64").astype(str)
    df["ground_truth"] = df["full_name_list"].apply(ground_truth_string)

    results = load_progress(config.GPT4O_GENERATED_CSV)
    done = {row["paperId"] for row in results}
    for i, row in enumerate(tqdm(df.itertuples(index=False), total=len(df), desc="Generating")):
        if row.paperId in done:
            continue
        question = create_question(row.title, row.year)
        results.append({
            "paperId": row.paperId,
            "citation": row.citationCount,
            "citation_bin": row.citation_bin,
            "field": row.field,
            "question": question,
            "answer": row.ground_truth,
            "gpt_answer": ask(client, build_generation_prompt(question)),
        })
        if (i + 1) % SAVE_EVERY == 0:
            pd.DataFrame(results).to_csv(config.GPT4O_GENERATED_CSV, index=False)
        time.sleep(SLEEP_BETWEEN_CALLS)
    pd.DataFrame(results).to_csv(config.GPT4O_GENERATED_CSV, index=False)
    print(f"Saved {len(results)} answers to {config.GPT4O_GENERATED_CSV}")


def run_self_evaluation(client: openai.OpenAI) -> None:
    """Score every generated answer with the self-evaluation prompt."""
    generated = pd.read_csv(config.GPT4O_GENERATED_CSV)
    results = load_progress(config.GPT4O_SELF_EVAL_CSV)
    done = {row["paperId"] for row in results}
    for i, row in enumerate(tqdm(generated.to_dict("records"), desc="Self-evaluating")):
        if row["paperId"] in done:
            continue
        prompt = build_self_evaluation_prompt(row["question"], row["answer"], row["gpt_answer"])
        results.append({**row, "evaluation": evaluate_with_retry(client, prompt)})
        if (i + 1) % SAVE_EVERY == 0:
            pd.DataFrame(results).to_csv(config.GPT4O_SELF_EVAL_CSV, index=False)
        time.sleep(SLEEP_BETWEEN_CALLS)
    pd.DataFrame(results).to_csv(config.GPT4O_SELF_EVAL_CSV, index=False)
    n_failed = sum(r["evaluation"] == FAILED_EVALUATION for r in results)
    print(f"Saved {len(results)} evaluations to {config.GPT4O_SELF_EVAL_CSV} ({n_failed} unparseable)")


def main() -> None:
    """Parse arguments and run the requested step(s)."""
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--step", choices=["generate", "evaluate", "all"], default="all")
    args = parser.parse_args()

    if not os.environ.get("OPENAI_API_KEY"):
        sys.exit("ERROR: set OPENAI_API_KEY (see .env.example).")
    config.GPT4O_RECALL_DIR.mkdir(parents=True, exist_ok=True)
    client = openai.OpenAI()

    if args.step in ("generate", "all"):
        run_generation(client)
    if args.step in ("evaluate", "all"):
        run_self_evaluation(client)


if __name__ == "__main__":
    main()
